Major refactors
- moved dotdeploy-prepare and dotdeploy-deploy into lib/ folder
- Removed lib/init.sh
- Source individual lib/ files on a per use basis
- Build .deb packages in temp folder
- Add gitignore
- Add more metadata to DB

diff --git a/dotdeploy b/dotdeploy
--- a/dotdeploy
+++ b/dotdeploy
@@ -5,19 +5,23 @@ set -o errexit
 # Terminate if variable is used which has not been initialized
 set -o nounset
 
+# DEPRECATED 2024-01-12: Check for minimum version of jq >= 1.7
+if command -v jq >/dev/null; then
+    jq_ver="$(jq --version)"
+    jq_ver="${jq_ver#jq-}"
+    if ! printf "1.7\n%s\n" "$jq_ver" | sort -V -C; then
+        echo "Error: jq version is older than 1.7!"
+        unset -v jq_ver
+        exit 1
+    fi
+    unset -v jq_ver
+fi
+
+DOTDEPLOY_VERSION="0.2"
+readonly DOTDEPLOY_VERSION
+
 # FIXME: Move to better place
 # set -o xtrace
-DOTDEPLOY_TMP_DIR=$(mktemp --directory -t dotdeploy.XXXXXXX)
-readonly DOTDEPLOY_TMP_DIR
-
-# Source library
-source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")"/lib/common.sh
-
-# Collect environment information
-host_name="${host_name:-$(dd::common::detect_host)}"
-host_os="${host_os:-$(dd::common::detect_os)}"
-is_container="${is_container:-$(dd::common::detect_container)}"
-dryrun=0
 
 # Print usage to stdout.
 # Arguments:
@@ -26,7 +30,7 @@ dryrun=0
 #   Print usage with examples.
 show_help() {
     cat << EOF
-DotDeploy - Deploy dotfiles and system configuration
+Dotdeploy - Deploy dotfiles and system configuration
 
 Usage:
 
@@ -40,6 +44,8 @@ Choose one of the available commands:
 
 Options:
        --dry-run            Only print the commands
+
+Dotdeploy version: $DOTDEPLOY_VERSION
 EOF
 }
 
@@ -50,47 +56,69 @@ if [[ $# -eq 0 ]]; then
     exit
 fi
 
-# Activate logging
-dd::log::log_on
-
-dd::log::log-info "Host is $host_name"
-dd::log::log-info "Running $host_os"
-dd::log::log-info "Are we in a container? $is_container"
-
-dd::log::log-info "TMP directory set to: $DOTDEPLOY_TMP_DIR"
+dd_dryrun=0
+dd_deploy=0
 
 # Parse arguments
 unknown=()
-while [[ $# -gt 0 ]]; do
+
+while (( $# > 0 )) ; do
     case $1 in
         help | --help | -h)
-            # Deactivate logging
-            dd::log::log_off
             # Show help message
             show_help
             exit 0
             ;;
         --dry-run)
-            shift
-            dryrun=1
+            dd_dryrun=1
             ;;
         deploy)
             # Deploy modules
-            shift # past argument
-            source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")"/dotdeploy-deploy
-            dotdeploy_deploy "$@"
+            dd_deploy=1
+            shift
             break
+            ;;
+        --)
+            shift
+            break
+            ;;
+        -*)
+            printf >&2 "Error: Unknown option %s\n" "$1"
+            show_help
+            exit 1
             ;;
         *)  # Unknown option
             unknown+=( "$1" )
-            shift
             ;;
     esac
+    # Shift to next argument
+    shift
 done
 
-set -- "${unknown[@]}" # Restore unknown arguments
 if [[ ! ${#unknown[@]} -eq 0 ]]; then
-    dd::log::log-fail "Invalid command: ${unknown[*]}"
+    echo "Error: Invalid command ${unknown[*]}"
     show_help
     exit 1
+elif [[ $dd_deploy -eq 1 ]]; then
+    # Libraries
+    source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")"/lib/common.sh
+    source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")"/lib/log.sh
+
+    # Collect environment information
+    dd_host_name="${dd_host_name:-$(dd::common::detect_host)}"
+    dd_distro="${dd_distro:-$(dd::common::detect_distro)}"
+    dd_is_container="${dd_is_container:-$(dd::common::detect_container)}"
+
+    # Activate logging
+    dd::log::log_on
+
+    # Print basic information
+    dd::log::log-info "$(printf '%-22s: %s' "Hostname" "$dd_host_name")"
+    dd::log::log-info "$(printf '%-22s: %s' "Distribution" "$dd_distro")"
+    dd::log::log-info "$(printf '%-22s: %s' "Container environment" "$dd_is_container")"
+    dd::log::log-info "TMP directory set to $DOTDEPLOY_TMP_DIR"
+
+    # Start deployment
+    source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")"/lib/deploy.sh
+    dotdeploy_deploy "$@"
 fi
