sdboot-up: Implement shellcheck fixes

diff --git a/packages/gentoo/overlay/sys-boot/sdboot-up/files/sdboot-up b/packages/gentoo/overlay/sys-boot/sdboot-up/files/sdboot-up
--- a/packages/gentoo/overlay/sys-boot/sdboot-up/files/sdboot-up
+++ b/packages/gentoo/overlay/sys-boot/sdboot-up/files/sdboot-up
@@ -2,8 +2,8 @@
 
 # Make sure we are root
 if [[ $EUID -ne 0 ]]; then
-   echo "Must be run as root, aborting."
-   exit 1
+  echo "Must be run as root, aborting."
+  exit 1
 fi
 
 # Exit on any error (-e), treat unset variables as errors (-u), and make sure
@@ -19,7 +19,8 @@ KERNEL_NEW_NAMES=( "gentoo-dist" )
 # Check if the config file exists, and source it if it does
 CONFIG_FILE="/etc/default/sdboot-up"
 if [[ -f "$CONFIG_FILE" ]]; then
-    source "$CONFIG_FILE"
+  # shellcheck source=/etc/default/sdboot-up
+  source "$CONFIG_FILE"
 fi
 
 # Define the source and destination directories
@@ -28,50 +29,50 @@ dst_dir="/boot/efi"
 
 # Function to get the highest version from a sorted list
 get_highest_version() {
-    local sorted_versions=("$@")
-    echo "${sorted_versions[-1]}"
+  local sorted_versions=( "$@" )
+  echo "${sorted_versions[-1]}"
 }
 
 # Iterate over each KERNEL_NAME
 for idx in "${!KERNEL_NAMES[@]}"; do
-    name="${KERNEL_NAMES[$idx]}"
-    version="${KERNEL_VERSIONS[$idx]}"
-    target="${KERNEL_NEW_NAMES[$idx]}"
+  name="${KERNEL_NAMES[$idx]}"
+  version="${KERNEL_VERSIONS[$idx]}"
+  target="${KERNEL_NEW_NAMES[$idx]}"
 
-    echo "Looking for files matching $name ..."
-    # Use regex to match files with name pattern
-    matching_files=($(find "$src_dir" -maxdepth 1 -printf "%f\n" | grep -E "${name}"))
+  echo "Looking for files matching $name ..."
+  # Use regex to match files with name pattern
+  mapfile -t matching_files < <(find "$src_dir" -maxdepth 1 -printf "%f\n" | grep -E "${name}")
 
-    # If version is empty, get the highest version number
-    if [[ -z "$version" ]]; then
-        # Extract the versions and sort them
-        sorted_versions=($(printf "%s\n" "${matching_files[@]}" | grep -oP '(?<=-)[0-9.]+(?=-)' | sort -V))
-        highest_version=$(get_highest_version "${sorted_versions[@]}")
-    else
-        echo "Looking for files matching $version ..."
-        sorted_versions=($(printf "%s\n" "${matching_files[@]}" | grep -oP "(?<=-)$version[0-9.]*(?=-)" | sort -V))
-        highest_version=$(get_highest_version "${sorted_versions[@]}")
+  # If version is empty, get the highest version number
+  if [[ -z "$version" ]]; then
+    # Extract the versions and sort them
+    mapfile -t sorted_versions < <(printf "%s\n" "${matching_files[@]}" | grep -oP '(?<=-)[0-9.]+(?=-)' | sort -V)
+    highest_version=$(get_highest_version "${sorted_versions[@]}")
+  else
+    echo "Looking for files matching $version ..."
+    mapfile -t sorted_versions < <(printf "%s\n" "${matching_files[@]}" | grep -oP "(?<=-)${version}[0-9.]*(?=-)" | sort -V)
+    highest_version=$(get_highest_version "${sorted_versions[@]}")
+  fi
+
+  # Collect files which match version number
+  to_copy=()
+  for file in "${matching_files[@]}"; do
+    if [[ $file =~ $highest_version ]]; then
+      to_copy+=( "$file" )
     fi
+  done
 
-    # Collect files which match version number
-    to_copy=()
-    for file in "${matching_files[@]}"; do
-        if [[ $file =~ $highest_version ]]; then
-            to_copy+=("$file")
-        fi
-    done
+  if [[ "${#to_copy[@]}" -gt 0 ]]; then
+    echo "Found:"
+    printf '%s\n' "${to_copy[@]}"
+  else
+    echo "No files found matching $name."
+    continue
+  fi
 
-    if [[ -z "$to_copy" ]]; then
-        echo "No files found matching $name."
-        continue
-    else
-        echo "Found:"
-        printf '%s\n' "${to_copy[@]}"
-    fi
-
-    # Copy matching files to new folder
-    for file in "${to_copy[@]}"; do
-        new_name=$(echo "$file" | sed -E "s/${name}/${target}/" | sed -E "s/-[0-9.]+-/-/")
-        cp -v "$src_dir/$file" "$dst_dir/$new_name"
-    done
+  # Copy matching files to new folder
+  for file in "${to_copy[@]}"; do
+    new_name=$(echo "$file" | sed -E "s/${name}/${target}/" | sed -E "s/-[0-9.]+-/-/")
+    cp -v "$src_dir/$file" "$dst_dir/$new_name"
+  done
 done
